name: CI/CD for My Portfolio

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04  # Explicit version to avoid ubuntu-latest transition warnings

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deployment branch
          folder: .         # Folder containing static files
